#!/bin/sh

PATH=/sbin:/usr/sbin:/bin:/usr/bin

echo "Init Stage 1"

for f in /etc/runit/1.d/*.sh; do
	[ -r $f ] && source $f
done

echo "Init Stage 1 Done."

echo "Running oneshots"
# trigger oneshot
source /etc/runit/vars
cd "$basedir"
../scripts/run-oneshot
echo "Done."
